### ISSUE TITLE
Steam英文版支持

### ISSUE THREAD

**Issue by kurtwang0820** [OnmyojiX/yyx#13]
进程名字不一样
御魂之类的名字mapping

谢谢

**Comment by fluxxu** [comment]
如果只是进程名字不一样的话下个版本支持

**Comment by kurtwang0820** [comment]
御魂之类名字应该是英文的
个人猜测读取内存的方式应该一样

试过论坛里火电太热大佬的御魂导出器
能识别进程 但导出不了任何数据
不过御魂放大器可以正常用 所以猜测应该只是名字不一样

https://bbs.nga.cn/read.php?tid=15220479
https://bbs.nga.cn/read.php?tid=14794337

**Comment by fluxxu** [comment]
名字倒是无所谓，导出的数据里面只有数字ID
中文全都是前端显示的时候后加上的
应该问题不大

**Comment by fluxxu** [comment]
测试过了 可以读取

**Comment by kurtwang0820** [comment]
太好了 给大佬赞一个

**Comment by fluxxu** [comment]
已经发布，请到网盘下载
yyx-snapshot-0.2.0-Steam-20190331.zip
