### ISSUE TITLE
台服无法使用

### ISSUE THREAD

**Issue by shouyun7** [OnmyojiX/yyx#21]
Facebook Gameroom无法使用导出
一直卡在Connecting...
请大佬帮忙，感谢

**Comment by fluxxu** [comment]
你用的是
yyx-snapshot-0.2.0-FacebookGameroom
吗？
我测试了一下我这里可以啊。
是什么操作系统？

**Comment by shouyun7** [comment]
不知道为什么可以用了
我用的是Windows10 64-bit
感谢帮忙，不好意思打扰了
