### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by lordrou** [OnmyojiX/yyx#23]
https://bbs.nga.cn/read.php?tid=16557282
导出快照失败了，说客户端不对，但是yys已经更新到最新版了
![WechatIMG1600](https://user-images.githubusercontent.com/31644804/60984303-1379f300-a36e-11e9-9950-ec987d08588c.png)

**Comment by fluxxu** [comment]
重新下载yyx-snapshot 0.6
你这是0.5版
