### ISSUE TITLE
Mac下报错

### ISSUE THREAD

**Issue by dawnos** [OnmyojiX/yyx#27]
打开顺序：打开MuMu，登陆游戏，然后运行`yyx-snapshot`。

错误如下：

~/Downloads/yyx-snapshot-0.9.0-macOS »  ./yyx-snapshot    tangli@TangLi-Mac
Password:
痒痒熊快照
https://nga.178.com/read.php?tid=16557282
****************************************
Output dir: "/Users/tangli/Downloads/yyx-snapshot-0.9.0-macOS"
Bridge version: 0.9.0
Generating snapshot...
Initializing...
Connecting to MuMu...
Pushing YYX bridge...
Running YYX bridge...
Parsing data...
Error: Resolve lib path failed.

想问一下有没有解决办法？

**Comment by fluxxu** [comment]
你好
我今天也遇到一次这个问题，但是重新开就好了，你重新开的话一直都不行吗？

**Comment by dawnos** [comment]
你好！请问是重开MuMu 吗？如果是的话，我已经试过了，加sudo权限也不行。
顺便问一句，这个导出工具的代码有开源吗？有的话我可以自己找一下原因。

**Comment by fluxxu** [comment]
研究了一下终于稳定重现了这个错误
已经在0.9.1修复
https://github.com/OnmyojiX/yyx/releases/download/0.9.0/yyx-snapshot-0.9.1-macOS.zip

不需要sudo权限的。
这个导出工具没有开源，因为官方表示了关切 -.-

**Comment by dawnos** [comment]
试了一下还是不行。有时候会变成另一个错误：

痒痒熊快照
https://nga.178.com/read.php?tid=16557282
****************************************
Output dir: "/Users/tangli/Downloads/yyx-snapshot-0.9.1-macOS"
Bridge version: 0.9.1
Generating snapshot...
Initializing...
Connecting to MuMu...
Pushing YYX bridge...
Running YYX bridge...
Parsing data...
Error: Type mismatch.

同时，MuMu里的YYS会退出。
请问你说的重开指的是重开MuMu？0.9.0下你的MuMu中的YYS会退出吗？

**Comment by fluxxu** [comment]
问题已经修复
请下载0.9.2
https://github.com/OnmyojiX/yyx/releases/download/0.9.0/yyx-snapshot-0.9.2-macOS.zip

谢谢反馈！

**Comment by dawnos** [comment]
json可以导出了。MuMu中的YYS还是会闪退，但不影响导出。

谢谢！

**Comment by fluxxu** [comment]
闪退是为了防止官方检查到yyx导致误封，所以先下手为强干掉了阴阳师。
