### ISSUE TITLE
请教这些游戏数据是如何得到的？

### ISSUE THREAD

**Issue by zhongjianhua163** [OnmyojiX/yyx#28]
学习一下。。。

**Comment by zhongjianhua163** [comment]
...
我好像看到了一个网页API接口...

**Comment by fluxxu** [comment]
获取游戏数据的源码没有开源，因为涉及官方不想公开的加密什么的。
如果你想研究的话建议你参考这篇文章：
https://docs.ioin.in/writeup/blog.fatezero.org/_2017_01_14_decrypt_onmyoji_/index.html
