### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by bephbin51695** [OnmyojiX/yyx#31]
痒痒熊快照
https://nga.178.com/read.php?tid=16557282
****************************************
装载中...
Bridge版本: 0.99.2
正在生成快照...
连接中...
读取中...
错误: list index out of range

**Comment by fluxxu** [comment]
这种错误一般重启游戏再导出一次就可以解决
还有可能是帐号比较新，有些数据还没有初始化

**Comment by fluxxu** [comment]
先关闭了，如果一直有这个错误可以reopen
