### ISSUE TITLE
导出失败

### ISSUE THREAD

**Issue by Bill025** [OnmyojiX/yyx#32]
Bridge版本: 0.99.2
正在生成快照...
连接中...
读取中...
错误: 进程异常终止，请确保你使用的是官网最新版的阴阳师: 0

已更新最新win10客户端仍失败。

**Comment by fluxxu** [comment]
这个问题一直以来都有人反馈，一般是因为没有用管理员权限运行阴阳师导致的
如果需要的话可以联系我我们联机调试
