### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by samefishyoung** [OnmyojiX/yyx#33]
我算过御魂属性，太费时间了。
建议提供只检索有4次或5次收益的御魂，次数可让用户选择。
简单说就是提供一个1分钟内出结果，但不一定是最优解的思路，一个字，快，有东西才能留住人。

**Comment by fluxxu** [comment]
你好 你是想反馈给御魂hub作者吧？
这里
https://yuhunhub.gitee.io/#/about
<https://yuhunhub.gitee.io/#/about?u=yyx_snapshot_20190908224523_16001_42499>

Close #33
