### ISSUE TITLE
MacOS下不能导出御魂

### ISSUE THREAD

**Issue by yuhao-nyc** [OnmyojiX/yyx#34]
之前用过很多次，每次都可以成功导出御魂，今天不知道为什么打开yyx-snapshot。就收到这个error.
Error: Adb error: Io(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })

**Comment by fluxxu** [comment]
<img width="696" alt="Screen Shot 2020-01-23 at 1 27 12 PM" src="https://user-images.githubusercontent.com/4956828/73012357-1a38f680-3de4-11ea-9587-4e6d4e0f567e.png">
不妙，内核更新了
需要研究一下是不是不兼容了

**Comment by fluxxu** [comment]
@yuhao-nyc 
我测试了最新版
https://github.com/OnmyojiX/yyx/releases/download/0.99.3/yyx-snapshot-0.99.0-macOS.zip
可以导出没有问题
可能你那边需要重启一下mumu模拟器

**Comment by yuhao-nyc** [comment]
@fluxxu 重新下载MUMU更新以后好了，感恩！
