### ISSUE TITLE
yyx-snapshot能否支持sandboixe沙箱里的阴阳师pc端

### ISSUE THREAD

**Issue by ojeo** [OnmyojiX/yyx#35]
yyx-snapshot能否支持sandboixe沙箱里的阴阳师pc端
sandboixe免费，下载地址：
https://www.sandboxie.com/
谢谢

**Comment by fluxxu** [comment]
这个要支持工作量应该比较大，暂时不考虑
如果你只是为了多开，可以用yyx多开
https://nga.178.com/read.php?tid=17002730
