### ISSUE TITLE
十分好奇读取御魂数据是怎么做到的 希望大佬指点一下

### ISSUE THREAD

**Issue by pk2373** [OnmyojiX/yyx#40]
感激不尽

**Comment by fluxxu** [comment]
Windows版是注入dll，在阴阳师的python虚拟机运行自定义代码获取御魂数据，然后用pipe发出去
Mac版是用adb协议在MuMu执行一个文件，这个文件往阴阳师进程注入一个so文件，然后在阴阳师的python虚拟机运行自定义代码获取御魂数据，然后用pipe发出去，再adb返回
总之比较麻烦，而且细节官方不让我多讲
