### ISSUE TITLE
facebookGameroom 小小修改

### ISSUE THREAD

**Issue by BillballSun** [OnmyojiX/yyx#42]
似乎网易将主程序名称从 client.exe 改成了 aclient.exe ( 骚操作
然后 snapshot 宕机了，为难
大佬小改一下吧，谢谢了

[ 看不懂 Rust ... 害怕

**Comment by fluxxu** [comment]
[yyx-snapshot-1.6.2-FacebookGameroom.zip](https://github.com/OnmyojiX/yyx/files/4924768/yyx-snapshot-1.6.2-FacebookGameroom.zip)
好了 我测试似乎可以了
